### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by iscaleira** [fightnight/fightnight-addons#25]
First of all thank you very much for making fightnight addon available, its my favorite xbmc addon by far...good job , I was wondering if there is a fix for some of my favorite channels do not seem to work for me , one of them being Benfica TV  this channel has never worked for me, I was wondering if there is a fix I can attempt on my XBMC.

**Comment by fightnight** [comment]
Boas,

O funcionamento dos canais depende de quem transmite e do suporte do kodi aos servidores. O addon não é responsável pelo conteúdo dos sites e em nada está associado a eles.
