### ISSUE TITLE
TV Portuguesa

### ISSUE THREAD

**Issue by miguelcobain** [fightnight/fightnight-addons#26]
O addon Tv Portuguesa não parece estar a funcionar com RPi e OpenELEC 5. Actualizei a librtmp correctamente.

É algum problema com a librtmp para RPi? Posso compilá-la e disponibilizar, se necessário.

**Comment by miguelcobain** [comment]
Em Linux e Windows também não funciona. Fica eternamente em "Working..." após selecionar a stream.
Fiz update da librtmp pelo addon "K0di tools".

**Comment by fightnight** [comment]
Testa a nova actualização com o novo librtmp.

Mais info: http://bit.ly/actualizar_lib

**Comment by miguelcobain** [comment]
Impecável.

@i96751414, talvez valha a pena actualizar o K0di tools?

**Comment by fightnight** [comment]
O k0di tools já tem a lib mais recente ;)
