### ISSUE TITLE
Wareztuga - Modo Biblioteca

### ISSUE THREAD

**Issue by Spartan17** [fightnight/fightnight-addons#28]
Boas, 
Detectei um erro um bocado estranho no modo biblioteca: 
Quando o user subscreve duas séries com nomes iguais Ex: Knight Rider (1963) e Knight Rider (2008), o addon sobrepõe ambas as séries, em vez de as separar.

**Comment by fightnight** [comment]
Tens razão, estive a ver e preciso de fazer imensas alterações estruturais para suportar o modo de biblioteca para 2 séries com o mesmo nome. Estive a dar uma olhadela e só acontece com essa série, logo vão suspender este fix para já.

**Comment by Spartan17** [comment]
Pois, é compreensível. Vou tentar um quick fix e remover ambas as séries da biblioteca, apagar os ficheiros da biblioteca na pasta do add-on, subscrever a série que só tem uma temporada, mudar o nome da pasta e depois subscrever a maior, para ver se funciona. Thanks!
