### ISSUE TITLE
okgoals nao funciona

### ISSUE THREAD

**Issue by haskily** [fightnight/fightnight-addons#30]
boa noite fightnight, o meu addon okgoals nao funciona. uso o kodi 14.1, e antes d ter o kodi usava o xmbc e funcionava bem, nao percebo o problema visto que todos os outros addons funcionam.. aparece-me sempre o msm erro "no compatible server available" sempre que tento abrir um link dos golos, sem execpção..

Se pudesses agradecia a ajuda,

keep it up, cumprimentos

**Comment by haskily** [comment]
entao? :(

**Comment by sbalmeida** [comment]
Tb me acontece o mesmo. Já existe solução para este problema? Cumprimentos.

**Comment by fightnight** [comment]
Vou verificar.

**Comment by haskily** [comment]
obrigado, se serve de info ja tentei em 2 tmvs e 1 tablet, oneplus one e
nexus 5, e tb o tablet bq edison 2.. e no msm acontece o msm, da essa msg d
errs, no compatible server available em todos os jogos.

muito obrigado e dsclp a maçada :)
Em 10/03/2015 18:50, "fightnight" <notifications@github.com> escreveu:

**Comment by fightnight** [comment]
Verifica se já está resolvido na última versão.

**Comment by haskily** [comment]
Boa tarde,

agora sim, na 2.0.1 esta a funcionar na perfeição. muito obrigado :)
