### ISSUE TITLE
[Abelhas] Erro de script

### ISSUE THREAD

**Issue by calhaus** [fightnight/fightnight-addons#43]
Olá,
O meu addon do abelhas deixou de funcionar.
 Dá sempre erro de script! 
Tanto em linux mint como no rpi2 com xbian. Ambos com Kodi 14.2

Debug log no rpi2:
http://pastebin.com/7TWx43jp

Offtopic: Fiz uma fanart super simples para usar com o addon super favourites visto que o addon não tem fan art. Fica aqui o link se quiseres addicionar ao addon: http://i.imgur.com/06FbqhB.jpg ;)

**Comment by fightnight** [comment]
Thanks, verifica se está a funcionar na última versão.

Se quiseres fazer uma fanart 1280x720 e icon 256x256 para o novo abelhas/minhateca fico agradecido.

**Comment by JFM0791** [comment]
Olá, 

O Abelhas está a funcionar bem, e a integração do MinhaTeca é muito boa também, mas este último não está a funcionar. Eu sei que ainda está em actualização e deve ser por isso.

Para já os problemas que detectei que já devem ser do vosso conhecimento, no MinhaTeca:

- Não aparece nada dentro das pastas do menu inicial
- Falta a pasta "a minha conta"
- Falta a pasta "Ir para um usuário" 
- Na pasta "Atalhos" aparecem os atalhos do Abelhas

Problemas que serão corrigidos certamente com o tempo e vossa disponibilidade. Quero agradecer tudo o que tem feito.

um abraço

Fernando
