### ISSUE TITLE
Não é um problema, mas melhoria

### ISSUE THREAD

**Issue by Leinad4Mind** [fightnight/fightnight-addons#48]
Poderias adicionar, já agora o Toutbox.fr. A frança é um país com muitos emigrantes, e ter o abelhas a permitir aceder a conteúdos de francófonos seria muito porreiro também.

Quanto ao nome do programa, quase que ficaria um AbeTecaBox LOOL

Ou só "Abelhas" ficaria optimo! Os outros são cópias e seriam um complemento.

Abraço

EDIT: Fiz os pull requests, acho que não falhei em nada. Acabei por fazer para mim, e depois decidi partilhar. ^^ 

Sei que estás a trabalhar num novo, mas pode ser que isto te dê novas ideias :P

**Comment by Leinad4Mind** [comment]
Fiz os pull requests, acho que não falhei em nada. Acabei por fazer para mim, e depois decidi partilhar. ^^

**Comment by fightnight** [comment]
Está nice.. já tinha a ideia de fazer isso e adicionar esse (e outros clones) para a nova versão e alterar o addon para algo mais global, mas visto que fizeste já é bem bacano..

Só que o tempo agora anda escasso para pegar nisto.. Vamos aguardar pelos progressos do mafarricos.. ty malta

**Comment by Mafarricos** [comment]
https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/commit/2e0b1c6f7da1212d284470ab1c2d4dcefea43508

Lolabits e toutbox adicionados.

**Comment by Mafarricos** [comment]
Mudei o nome do addon para Abelhas e Clones ;)
A adição à biblioteca parece-me que já está fixe.

**Comment by jorgeavlobo** [comment]
Mafarricos: A adição já está mesmo?
Podes indicar à comunidade onde estão as instruções para o fazer?
Podes fechar um dos tópicos dos Issues relativamente à Library.

**Comment by Mafarricos** [comment]
@jorgeavlobo podes instalar o meu repo: https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/raw/master/repo/repository.mafarricosDev.xbmc/repository.mafarricosDev.xbmc-0.0.1.zip que instala para a versão do abelhas que eu ando a trabalhar.
Em breve o fightnight deve incorporar na versão dele ;)

**Comment by jorgeavlobo** [comment]
Dude, you're the best!
Sabes que o facto de se poder adicionar os ficheiros à biblioteca vai aumentar a "visibilidade"/popularidade da aplicação de uma forma exponencial se o pessoal souber configurar aquilo.
Não estou no meu PC habitual, podes-me dar os passos em meia dúzia de palavras para adicionar os filmes à biblioteca? Gostava de testar isto já amanhã e dar-te feedback.

**Comment by Mafarricos** [comment]
Nas settings do addon, configuras a pasta que queres meter os .strm, adicionas a mesma pasta à biblioteca, como se faz em outros addons.

Depois em cima de um ficheiro de video passas a ter a opção de adicionar à biblioteca.

**Comment by jorgeavlobo** [comment]
Peço desculpa por não poder testar agora, mas aqui vai uma pergunta:
- Vou ter que adicionar depois os ficheiros de vídeo um a um? Eu tenho alguns milhares de ficheiros...

**Comment by jorgeavlobo** [comment]
Editei o comentário anterior.

**Comment by Mafarricos** [comment]
Isso é daquelas coisas que quando fiz, nem me passou pela cabeça.
Como para já o adicionar à biblioteca só funciona no ficheiro, tinhas que ter uma pasta só com vídeos, para algo desse género funcionar.
O problema é que o abelhas não é um site de filmes, logo a estrutura que cada um mantém no seu abelhas tem formas diferentes de ter os ficheiros.

Portanto não sei até que ponto é mesmo viável, a ser só com uma estrutura especifica.

**Comment by jorgeavlobo** [comment]
Por exemplo:
Uma opção para adicionar todos os ficheiros *.avi *.mkv *.mp4 (etc) da pasta X e todas as subfolders, à biblioteca.

**Comment by jorgeavlobo** [comment]
right click numa folder > adicionar todos os ficheiros de video à biblioteca.

**Comment by Mafarricos** [comment]
A teoria é simples a prática é que nem por isso :P
Já que o addon não faz isso por defeito, quando entras numa pasta ele mostra-te as pastas e ficheiros dessa pasta, não percorre tudo até ao fim. E isso até se pode tornar um pouco pesado.

**Comment by jorgeavlobo** [comment]
Claro que tinhas ponderado isso, I was just checking.
Vou adicionar todos os filmes um a um, também só me vai custar uma vez e depois fica 5 estrelas.
Quando formatar o PC, existe maneira de salvar as settings?

**Comment by Mafarricos** [comment]
Guardas a pasta onde criou os .strm, e dps voltas a adicionar à biblioteca.

**Comment by jorgeavlobo** [comment]
O Kodi em si deve ter algures uma opção para salvar a biblioteca, depois pesquiso. Quero evitar adicioná-los um a um novamente.
Thanks!

**Comment by jorgeavlobo** [comment]
http://kodi.wiki/view/backup#Backing_up_the_video_library

**Comment by ffsi** [comment]
Não sei se é viável, mas nesse mesmo molde dos filmes, poderia ter para as músicas.

**Comment by Mafarricos** [comment]
@ffsi, experimenta adicionar uma musica à biblioteca através de strm e vê se funciona...

**Comment by ffsi** [comment]
Criei o arquivo strm usando o próprio programa, como se o arquivo fosse um filme, depois pelo gerenciador passei ele para pasta de músicas.

Os arquivos aparecem corretamente no Músicas, entretanto não consigo reproduzir a pasta... Somente selecionado arquivo por arquivo, a criação de playlist também não funciona.

Pensando em uma alternativa a isso, seria uma melhoria no " criar playlist ", de forma que se possa adicionar todos arquivos de mais de uma pasta.
Atualmente ao executar a operação em outra pasta, sobrepõe a playlist atual.

**Comment by Mafarricos** [comment]
Até pode dar para adicionar o mp3 como strm mas não vai aparecer a informação porque para os mp3 ele vai buscar o ID ao próprio mp3 e tu no strm não consegues isso.
