### ISSUE TITLE
"Watch Trailer"

### ISSUE THREAD

**Issue by jorgeavlobo** [fightnight/fightnight-addons#53]
Did anyone notice that you can no longer watch movie trailers since this last update?
It is the same on my Minix NEO X-8H PLUS and also on my computer.
Before this last update, if I right clicked on a movie folder, one of the options I have is "Watch Trailer", and now it doesn't work.

Cheers,
JL

**Comment by Mafarricos** [comment]
Em qual addon?

**Comment by jorgeavlobo** [comment]
Abelhas.

**Comment by Mafarricos** [comment]
O meu PR deve resolver isso ;)

**Comment by jorgeavlobo** [comment]
Many thanks!
