### ISSUE TITLE
A lista de canais é agora limitada aos canais publicos

### ISSUE THREAD

**Issue by aboimpinto** [fightnight/fightnight-addons#58]
parece existir um problema a carregar a lista de canais, pois, só aparece os canais relacionados com RTP, SIC e TVI.

obrigado

**Comment by Mafarricos** [comment]
Viste o changelog do addon?

**Comment by aboimpinto** [comment]
?? onde isso está!?!
que informação tem lá??!

**Comment by Mafarricos** [comment]
https://github.com/fightnight/fightnight-addons/blob/master/plugin.video.tvpor/changelog.txt

**Comment by aboimpinto** [comment]
obrigado .. 

isto não é nada bom ... vivo em Zurique e está era a unica forma de manter contacto com os canais da TV Cabo!
que vergonha!

**Comment by fightnight** [comment]
Vergonha! Drama! Horror! E gratuito..
