### ISSUE TITLE
Abelhas : Menu de contexto

### ISSUE THREAD

**Issue by pmos69** [fightnight/fightnight-addons#60]
Menu de contexto de ficheiros apenas com 10 elementos.
"Ver trailer", "adicionar atalho" e "transferir ficheiro" não ficam visiveis.
Se comentar quaiquer outros 3 items anteriores da lista no default.py, já aparecem estes 3 items.

 Kodi 15.0-RC2

**Comment by Mafarricos** [comment]
Vou dar uma vista de olhos, ou seja existe limitação de 10 opções...

**Comment by pmos69** [comment]
Parece que sim: http://forum.kodi.tv/showthread.php?tid=225748

Só com um sub-menu, ou coisa do género...

**Comment by fightnight** [comment]
Corrigido na última versão v1.1.2
