### ISSUE TITLE
TV Portuguesa not updating

### ISSUE THREAD

**Issue by jcnventura** [fightnight/fightnight-addons#62]
Olá,

There's a new version here in github, which is not reflected in the repo at https://fightnightkodi.svn.codeplex.com/svn/addons/addons.xml

Can you fix that, so that my OSMC install auto-updates?

**Comment by fightnight** [comment]
Novo repositório disponivel (v1.6)

https://raw.githubusercontent.com/fightnight/f-base/master/repository.fightnight/repository.fightnight-1.6.zip
