### ISSUE TITLE
Not available retry later

### ISSUE THREAD

**Issue by kz0** [fightnight/fightnight-addons#63]
Acontece com qualquer ficheiro que selecione.

Aqui vai parte do log:

22:35:47 T:139809263691520  NOTICE: -->Python Interpreter Initialized<--
22:35:48 T:139809263691520  NOTICE: Mode: 25
22:35:48 T:139809263691520  NOTICE: URL: http://abelhas.pt/x010/Privada/Videos/Movies/HD/Minions.2015.1080p.BluRay.x264-GECKOS/Minions.2015.1080p.BluRay.x264-GECKOS,172812136.mkv(video)
22:35:48 T:139809263691520  NOTICE: Name: Minions 2015 1080p BluRay x264-GECKOS
22:35:48 T:139809263691520  NOTICE: Name: None
22:35:48 T:139809263691520  NOTICE: Sem cookie. A iniciar login
22:35:48 T:139809263691520  NOTICE: x010
22:35:57 T:139809263691520  NOTICE: {"Type":"Window","Title":"<div class="winChBoxDownload">Download</div>","Content":"rnrn<p style="font-size:17px;color:#339999;text-align:center;">A iniciar download com a <b>Box</b>...</p>rnrnrnrn<div style="float:left;margin-left: 18px;">rn    <a href="javascript:;" class="DontUseBoxInSessionButton DontDownloadWithBox" ref="172812136"></a>rn    <span class="DontUseBoxInSessionButtonText"><span style="font-size:13px;font-weight:bold;">Fazer o upload de ficheiros sem usar a Box</span><br />(nesta sess„o)</span>rn    rn</div>rnrn<div style="clear:both; margin-top:10px;margin-left:15px;">rnrn    <div style="float: left; margin-right: 10px; padding-top: 15px; line-height: 13px; cursor: pointer;" class="chomikBoxCheckHideWindow">rn            <div id="cbHideBoxWin" style="width:13px; height:13px; float: left; margin-right: 5px;" class="fileItemSB">rn                <input id="dontShowBoxInSession" name="cbHideBoxWin" type="checkbox" />rn            </div>rn            <label for="dontShowBoxInSession">N„o mostrar novamente esta janela nesta sess„o.</label>rn    </div>rn    <div style="float:right; padding-top: 5px;">rn        <input type="reset" class="greenButtonCSS chomikBoxCloseBoxWindow" value="fechar"/>rn    </div>rn</div>rnrn<div style="clear: both"></div>rnrn<script type="text/javascript">rn    ch.UI.ChomikBox.ExecDownloadFile(u0027chomik://files/:172812136u0027);rn</script>","refreshTopBar":false,"IsSuccess":true,"Data":null,"ContainsCaptcha":false,"trackingCodeJS":null}
22:35:58 T:139810481571712  NOTICE: DVDPlayer: Opening:
22:35:58 T:139810481571712 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:35:58 T:139809934780160  NOTICE: Thread DVDPlayer start, auto delete: false
22:35:58 T:139809934780160  NOTICE: Creating InputStream
22:35:58 T:139809934780160   ERROR: Error on dvdnav_open
22:35:58 T:139809934780160   ERROR: CDVDPlayer::OpenInputStream - error opening []
22:35:58 T:139809934780160  NOTICE: CDVDPlayer::OnExit()
22:35:58 T:139810481571712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.abelhas/?url=http://abelhas.pt/x010/Privada/Videos/Movies/HD/Minions.2015.1080p.BluRay.x264-GECKOS/Minions.2015.1080p.BluRay.x264-GECKOS,172812136.mkv(video)&mode=25&name=Minions+2015+1080p+BluRay+x264-GECKOS]
22:35:58 T:139809934780160  NOTICE: Thread BackgroundLoader start, auto delete: false
22:35:58 T:139810481571712  NOTICE: CDVDPlayer::CloseFile()
22:35:58 T:139810481571712  NOTICE: DVDPlayer: waiting for threads to exit
22:35:58 T:139810481571712  NOTICE: DVDPlayer: finished waiting
22:35:58 T:139810481571712  NOTICE: CDVDPlayer::CloseFile()
22:35:58 T:139810481571712  NOTICE: DVDPlayer: waiting for threads to exit
22:35:58 T:139810481571712  NOTICE: DVDPlayer: finished waiting

**Comment by fightnight** [comment]
Resolvido na última versão. v1.1.2

**Comment by kz0** [comment]
Add-on actualizado para a última versão.

O erro continua a aparecer mas só para os ficheiros que se encontram na pasta privada protegidos por password. 

00:39:25 T:139903912367872  NOTICE: Thread BackgroundLoader start, auto delete: false
00:39:35 T:139903912367872  NOTICE: Thread LanguageInvoker start, auto delete: false
00:39:35 T:139903912367872  NOTICE: -->Python Interpreter Initialized<--
00:39:35 T:139903912367872  NOTICE: Mode: 25
00:39:35 T:139903912367872  NOTICE: URL: http://abelhas.pt/x010/Privada/Videos/TV/Arrow.S03.1080p.WEB-DL.DD5.1.H.264-BS/Arrow.S03E15.Nanda.Parbat.1080p.WEB-DL.DD5.1.H.264-BS,87794703.mkv(video)
00:39:35 T:139903912367872  NOTICE: Name: Arrow S03E15
00:39:35 T:139903912367872  NOTICE: Name: None
00:39:35 T:139903912367872  NOTICE: Sem cookie. A iniciar login
00:39:35 T:139903912367872  NOTICE: x010
00:39:40 T:139903912367872  NOTICE: {"Type":"Window","Title":"<div class="winChBoxDownload">Download</div>","Content":"rnrn<p style="font-size:17px;color:#339999;text-align:center;">A iniciar download com a <b>Box</b>...</p>rnrnrnrn<div style="float:left;margin-left: 18px;">rn    <a href="javascript:;" class="DontUseBoxInSessionButton DontDownloadWithBox" ref="87794703"></a>rn    <span class="DontUseBoxInSessionButtonText"><span style="font-size:13px;font-weight:bold;">Fazer o upload de ficheiros sem usar a Box</span><br />(nesta sess„o)</span>rn    rn</div>rnrn<div style="clear:both; margin-top:10px;margin-left:15px;">rnrn    <div style="float: left; margin-right: 10px; padding-top: 15px; line-height: 13px; cursor: pointer;" class="chomikBoxCheckHideWindow">rn            <div id="cbHideBoxWin" style="width:13px; height:13px; float: left; margin-right: 5px;" class="fileItemSB">rn                <input id="dontShowBoxInSession" name="cbHideBoxWin" type="checkbox" />rn            </div>rn            <label for="dontShowBoxInSession">N„o mostrar novamente esta janela nesta sess„o.</label>rn    </div>rn    <div style="float:right; padding-top: 5px;">rn        <input type="reset" class="greenButtonCSS chomikBoxCloseBoxWindow" value="fechar"/>rn    </div>rn</div>rnrn<div style="clear: both"></div>rnrn<script type="text/javascript">rn    ch.UI.ChomikBox.ExecDownloadFile(u0027chomik://files/:87794703u0027);rn</script>","refreshTopBar":false,"IsSuccess":true,"Data":null,"ContainsCaptcha":false,"trackingCodeJS":null}
00:39:40 T:139904504629120  NOTICE: DVDPlayer: Opening:
00:39:40 T:139904504629120 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
00:39:40 T:139903182530304  NOTICE: Thread DVDPlayer start, auto delete: false
00:39:40 T:139903182530304  NOTICE: Creating InputStream
00:39:40 T:139903182530304   ERROR: Error on dvdnav_open
00:39:40 T:139903182530304   ERROR: CDVDPlayer::OpenInputStream - error opening []
00:39:40 T:139903182530304  NOTICE: CDVDPlayer::OnExit()
00:39:40 T:139904504629120   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.abelhas/?url=http://abelhas.pt/x010/Privada/Videos/TV/Arrow.S03.1080p.WEB-DL.DD5.1.H.264-BS/Arrow.S03E15.Nanda.Parbat.1080p.WEB-DL.DD5.1.H.264-BS,87794703.mkv(video)&mode=25&name=Arrow+S03E15]
00:39:40 T:139903182530304  NOTICE: Thread BackgroundLoader start, auto delete: false
00:39:40 T:139904504629120  NOTICE: CDVDPlayer::CloseFile()
00:39:40 T:139904504629120  NOTICE: DVDPlayer: waiting for threads to exit
00:39:40 T:139904504629120  NOTICE: DVDPlayer: finished waiting
00:39:40 T:139904504629120  NOTICE: CDVDPlayer::CloseFile()
00:39:40 T:139904504629120  NOTICE: DVDPlayer: waiting for threads to exit
00:39:40 T:139904504629120  NOTICE: DVDPlayer: finished waiting

**Comment by Mafarricos** [comment]
Já experimentaste desativar a utilização da aplicação Box no site do abelhas?

**Comment by Mafarricos** [comment]
![image](https://cloud.githubusercontent.com/assets/2441379/11770737/1f5c4f9e-a1fe-11e5-94e5-77abd3efce2b.png)
Esses piscos desativados nas opções da conta?

**Comment by kz0** [comment]
Tinha o último activado por alguma razão. Não me lembrei disso.

Agora já está tudo ok. Obrigado pela paciência.
