### ISSUE TITLE
Request Add Radio and Change stream's to high quality

### ISSUE THREAD

**Issue by lxnunorodrigues** [fightnight/fightnight-addons#68]
Viva , hoje deparei com o plugin tem a radio saturno , infelizmente nao sei quem foi que o adicionou , fiquei desiludido , eu era um dos tecnicos responsaveis de som e a manutenção dos mesmos .
Apoós nos finais de 2013 vim para Braga , e gostaria de saber se podem adicionar a minha radio .
"Esporões Web Radio"

Os stream's são 
http://eswebradio.dtdns.net:8000   aacplus
http://eswebradio.dtdns.net:8080/live128   mp3

entretanto estive a ouvir o stream da mega Hits e tenho novo streams com qualidade , envio as que tenho com boa qualidade da varias radios ...

#EXTINF:-1, TSF | MP3 64 Kbps - Lisboa
http://tsfdirecto.tsf.pt/tsfdirecto.mp3
#EXTINF:-1, Radio Renascença | AAC 48 Kbps - Lisboa
http://11063.live.streamtheworld.com:80/RADIO_RENASCENCAAAC_SC
#EXTINF:-1, RFM | AAC 48 Kbps - Lisboa
http://7749.live.streamtheworld.com:80/RFMAAC_SC
#EXTINF:-1, Mega Hits | AAC 48 Kbps - Lisboa
http://7749.live.streamtheworld.com:80/MEGA_HITSAAC_SC
#EXTINF:-1, Radio Orbital | MP3 128 Kbps - Lisboa
http://centova.radios.pt:8401/stream
#EXTINF:-1, Kiss FM | AAC 128 Kbps - Albufeira
http://213.239.218.99:7104/stream

Quando actualizarem , se possível contactem-me , obrigado

**Comment by fightnight** [comment]
Não leves a mal mas vou ter de recusar este PR. O objectivo do addon como está reformulado agora é ir directamente à fonte onde estão os links de forma a estar sempre ON e funcional. Ao adicionar estes links manualmente, provavelmente vão existir pequenas alterações no link que requerem manutenção.

Recomendo que uses o livestream pro ou alguma lista própria para o efeito. Cumprimentos
